language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get install python-numpy python-scipy python-dev python-pip python-nose g++ libopenblas-dev git
install:
  - sudo pip install Theano --user
script:
  - python -m unittest classifier_test
