language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
script:
  - python -m unittest classifier_test
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
    